//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.BRM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AutorizacaoMensagemLog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AutorizacaoMensagemLog() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.BRM.AutorizacaoMensagemLog", typeof(AutorizacaoMensagemLog).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorização Mensagem - Gravação Banco Dados.
        /// </summary>
        internal static string ProcessoFase_Texto_AUTMSGLOG_INSERT {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_AUTMSGLOG_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorização Mensagem - Atualização Flag Processado.
        /// </summary>
        internal static string ProcessoFase_Texto_AUTZMSGLOG_FLAGPROCESSADO_UPDATE {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_AUTZMSGLOG_FLAGPROCESSADO_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enquadramento de Grupo por Faixa BIN.
        /// </summary>
        internal static string ProcessoFase_Texto_GRUPO_ENQUADRAMENTO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_GRUPO_ENQUADRAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indicadores de Performance.
        /// </summary>
        internal static string ProcessoFase_Texto_INDICADORES_PERFORMANCE {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INDICADORES_PERFORMANCE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão Interpretador - Criação.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERP_CARTAO_INTERP_INSERT {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERP_CARTAO_INTERP_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão Interpretador - Atualização.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERP_CARTAO_INTERP_UPDATE {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERP_CARTAO_INTERP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador - Acionamento.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_ACIONAMENTO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_ACIONAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Cartão Registradores Persistência.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_EXEC_CRTREGI_PERSISTIR {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_EXEC_CRTREGI_PERSISTIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Expressão.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_EXEC_EXPRESSAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_EXEC_EXPRESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Início.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_EXEC_INICIO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_EXEC_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Regras Grupo 000.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_EXEC_REGRAS_GRUPO000 {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_EXEC_REGRAS_GRUPO000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Trace Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_EXEC_TRACE_FLUSH {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_EXEC_TRACE_FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador - Regras Ativas - Obter.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_REGRAS_ATIVAS_OBTER {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_REGRAS_ATIVAS_OBTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interpretador Execução - Trace AutoExpurgo.
        /// </summary>
        internal static string ProcessoFase_Texto_INTERPRETADOR_TRACE_AUTOEXPURGO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_INTERPRETADOR_TRACE_AUTOEXPURGO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão - Concentrador Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CARTAO_CONCENTRADOR_GRAVACAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CARTAO_CONCENTRADOR_GRAVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem - Cartão - Obtenção dos Campos.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CARTAO_QUEBRA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CARTAO_QUEBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cliente - Concentrador Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CLIENTE_CONCENTRADOR_GRAVACAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CLIENTE_CONCENTRADOR_GRAVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem - Cliente - Obtenção dos Campos.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CLIENTE_QUEBRA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CLIENTE_QUEBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conta - Concentrador Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CONTA_CONCENTRADOR_GRAVACAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CONTA_CONCENTRADOR_GRAVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem - Conta - Obtenção dos Campos.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_CONTA_QUEBRA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_CONTA_QUEBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem Neural - Criação.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_NEURAL_INSERT {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_NEURAL_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem - Neural - Obtenção dos Campos.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_NEURAL_QUEBRA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_NEURAL_QUEBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Montagem Objeto AutorizaçãoMensagem Completo.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_OBJ_AUTZMSG_MONTAGEM {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_OBJ_AUTZMSG_MONTAGEM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação - Concentrador Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_TRANSACAO_CONCENTRADOR_GRAVACAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_TRANSACAO_CONCENTRADOR_GRAVACAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem - Transação - Obtenção dos Campos.
        /// </summary>
        internal static string ProcessoFase_Texto_MENSAGEM_TRANSACAO_QUEBRA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_MENSAGEM_TRANSACAO_QUEBRA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redes Neurais - Atualização.
        /// </summary>
        internal static string ProcessoFase_Texto_REDES_NEURAIS_ATUALIZA {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_REDES_NEURAIS_ATUALIZA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separação dos REGs da Mensagem.
        /// </summary>
        internal static string ProcessoFase_Texto_SEPARACAO_REGS {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SEPARACAO_REGS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Enquadramento de Grupo por Faixa BIN.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_GRUPO_ENQUADRAMENTO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_GRUPO_ENQUADRAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Cartão Interpretador - Criação.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERP_CARTAO_INTERP_INSERT {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERP_CARTAO_INTERP_INSERT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Cartão Interpretador - Atualização.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_CARTAO_INTERP_UPDATE {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_CARTAO_INTERP_UPDATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador Execução - Cartão Registradores Persistência.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_CRTREGI_PERSIST {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_CRTREGI_PERSIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador Execução - Expressão.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_EXPRESSAO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_EXPRESSAO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador Execução - Início.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_INICIO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_INICIO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador Execução - Regras Grupo 000.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_REGRAS_GRUPO000 {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_REGRAS_GRUPO000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador Execução - Trace Gravação.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_TRACE_FLUSH {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_EXEC_TRACE_FLUSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Interpretador - Regras Ativas - Obter.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_INTERPRETADOR_REGRAS_ATIVAS_OBTER {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_INTERPRETADOR_REGRAS_ATIVAS_OBTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simulação - Montagem Manual Objeto AutorizaçãoMensagem Completo.
        /// </summary>
        internal static string ProcessoFase_Texto_SIMUL_OBJ_AUTZMSG_MONTAGEM_MANUAL {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_SIMUL_OBJ_AUTZMSG_MONTAGEM_MANUAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação - Comando Online Acionado.
        /// </summary>
        internal static string ProcessoFase_Texto_TRANSACAO_COMANDOONLINE_ACIONADO {
            get {
                return ResourceManager.GetString("ProcessoFase_Texto_TRANSACAO_COMANDOONLINE_ACIONADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de Sistema.
        /// </summary>
        internal static string TipoErro_Texto_APPLICATION_FAIL {
            get {
                return ResourceManager.GetString("TipoErro_Texto_APPLICATION_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de Regra de Negócio.
        /// </summary>
        internal static string TipoErro_Texto_BUSINESS_FAIL {
            get {
                return ResourceManager.GetString("TipoErro_Texto_BUSINESS_FAIL", resourceCulture);
            }
        }
    }
}
