//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.BRM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Interpretador_Principal {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Interpretador_Principal() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.BRM.Interpretador_Principal", typeof(Interpretador_Principal).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhuma Regra Ativa no Grupo 000.
        /// </summary>
        internal static string AplicarRegrasAtivas_Producao_msg_Grupo000SemRegraAtiva {
            get {
                return ResourceManager.GetString("AplicarRegrasAtivas_Producao_msg_Grupo000SemRegraAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não existe nenhuma Regra Ativa no Grupo 000 deste Pacote de Simulação.
        /// </summary>
        internal static string AplicarRegrasAtivas_Simulacao_msg_Grupo000SemRegraAtiva {
            get {
                return ResourceManager.GetString("AplicarRegrasAtivas_Simulacao_msg_Grupo000SemRegraAtiva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///Não há Regras Ativas neste Pacote de Simulação.
        /// </summary>
        internal static string Interpretador_Principal_Simulacao_msg_SemRegrasAtivas {
            get {
                return ResourceManager.GetString("Interpretador_Principal_Simulacao_msg_SemRegrasAtivas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não.
        /// </summary>
        internal static string Nao {
            get {
                return ResourceManager.GetString("Nao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sim.
        /// </summary>
        internal static string Sim {
            get {
                return ResourceManager.GetString("Sim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ALERTA GERADO.
        /// </summary>
        internal static string TraceTexto_AlertaGerado {
            get {
                return ResourceManager.GetString("TraceTexto_AlertaGerado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMANDO ONLINE.
        /// </summary>
        internal static string TraceTexto_ComandoOnline {
            get {
                return ResourceManager.GetString("TraceTexto_ComandoOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condição Satisfeita?.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_CondicaoSatisfeita {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_CondicaoSatisfeita", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo AlfaNumérico.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_ConteudoAlfaNumerico {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_ConteudoAlfaNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo DataHora.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_ConteudoDataHora {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_ConteudoDataHora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conteúdo Numérico.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_ConteudoNumerico {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_ConteudoNumerico", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_Data {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Esta Transação foi considerada?.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_EstaTransacaoFoiConsiderada {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_EstaTransacaoFoiConsiderada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Período, no Passado, de Obtenção de Transações:.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_header1a {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_header1a", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to até.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_header1b {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_header1b", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qtde de Transações a serem consideradas.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_header2 {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_header2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transação ID.
        /// </summary>
        internal static string TraceTexto_FIMTRSCONTAR_IDTransacao {
            get {
                return ResourceManager.GetString("TraceTexto_FIMTRSCONTAR_IDTransacao", resourceCulture);
            }
        }
    }
}
