//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.BRM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RegraConstrutorExpressoes {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RegraConstrutorExpressoes() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.BRM.RegraConstrutorExpressoes", typeof(RegraConstrutorExpressoes).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando &apos;##TOKEN1##&apos; não pode exceder de 30 caracteres.
        /// </summary>
        internal static string GerarSintaxe_msg1001 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra &apos;##TOKEN1##&apos; não pode exceder de 40 caracteres.
        /// </summary>
        internal static string GerarSintaxe_msg1002 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal &apos;##TOKEN1##&apos; não pode exceder de 15 caracteres.
        /// </summary>
        internal static string GerarSintaxe_msg1003 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante &apos;##TOKEN1##&apos; não pode exceder de 40 caracteres.
        /// </summary>
        internal static string GerarSintaxe_msg1004 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua &apos;##TOKEN1##&apos; não pode exceder de 02 caracteres.
        /// </summary>
        internal static string GerarSintaxe_msg1005 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complemento &apos;##TOKEN1##&apos; não pode exceder de 80 caracteres considerando as aspas.
        /// </summary>
        internal static string GerarSintaxe_msg1006 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1007 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr complementos.
        /// </summary>
        internal static string GerarSintaxe_msg1101 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1102 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaxe do Comando IR PARA deve ser [ IR PARA ] [ REGRA ] [ = ] [ &lt;código do grupo&gt;&lt;código da regra&gt; ].
        /// </summary>
        internal static string GerarSintaxe_msg1201 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido para o Comando IR PARA. Deve ser &apos;=&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1202 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando IR PARA necessita, em Constante, do código da Regra.
        /// </summary>
        internal static string GerarSintaxe_msg1203 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando IR PARA. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1205 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto da Regra a ser desviada é &lt;código do grupo&gt;&lt;código da regra&gt;. Ex: 001000002 (9 números).
        /// </summary>
        internal static string GerarSintaxe_msg1206 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto da Regra a ser desviada é &lt;código do grupo&gt;&lt;código da regra&gt;. Ex: 001000002 (9 números).
        /// </summary>
        internal static string GerarSintaxe_msg1207 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1208 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Comando IR PARA não permite redirecionar o fluxo para uma Regra em outro Grupo.
        /// </summary>
        internal static string GerarSintaxe_msg1209 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Comando IR PARA permite apenas redirecionar o fluxo para uma Regra posterior a esta (número de regra maior).
        /// </summary>
        internal static string GerarSintaxe_msg1210 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Regra [ ##TOKEN1## ] não existe neste Pacote de Simulação.
        /// </summary>
        internal static string GerarSintaxe_msg1211 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Regra [ ##TOKEN1## ] não está ATIVA neste Pacote de Simulação.
        /// </summary>
        internal static string GerarSintaxe_msg1212 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Regra [ ##TOKEN1## ] não existe.
        /// </summary>
        internal static string GerarSintaxe_msg1213 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Regra [ ##TOKEN1## ] não está ATIVA.
        /// </summary>
        internal static string GerarSintaxe_msg1214 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaxe do Comando EXECUTE deve ser [ EXECUTE ] [ PREV ] [ = ] [ &lt;código do grupo&gt; ].
        /// </summary>
        internal static string GerarSintaxe_msg1301 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido para o Comando EXECUTE. Deve ser &apos;=&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1302 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando EXECUTE necessita, em Constante, do código do Grupo.
        /// </summary>
        internal static string GerarSintaxe_msg1303 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1303", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando EXECUTE. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1305 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1305", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto do GRUPO a ser executado é &lt;código do grupo&gt;. Ex: 001 (3 números).
        /// </summary>
        internal static string GerarSintaxe_msg1306 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1306", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto do GRUPO a ser executado é &lt;código do grupo&gt;. Ex: 001 (3 números).
        /// </summary>
        internal static string GerarSintaxe_msg1307 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1307", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1308 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1308", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Grupo [ ##TOKEN1## ] não existe.
        /// </summary>
        internal static string GerarSintaxe_msg1309 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1309", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Grupo [ ##TOKEN1## ] utilizado neste comando EXECUTE não é compatível com o Ambiente &apos;##TOKEN2##&apos; desta Regra.
        /// </summary>
        internal static string GerarSintaxe_msg1310 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1310", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sintaxe do Comando NEURALEXEC deve ser [ NEURALEXEC ] [ REDE ] [ = ] [ &lt;código da rede neural&gt; ].
        /// </summary>
        internal static string GerarSintaxe_msg1401 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido para o Comando NEURALEXEC. Deve ser &apos;=&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1402 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando NEURALEXEC necessita, em Constante, do código da Rede Neural.
        /// </summary>
        internal static string GerarSintaxe_msg1403 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando NEURALEXEC. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1405 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto da REDE NEURAL a ser executada é &lt;código da rede neural&gt;. Ex: 000001 (6 números).
        /// </summary>
        internal static string GerarSintaxe_msg1406 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto da REDE NEURAL a ser executada é &lt;código da rede neural&gt;. Ex: 000001 (6 números).
        /// </summary>
        internal static string GerarSintaxe_msg1407 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1407", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1408 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Rede Neural  [ ##TOKEN1## ] não existe.
        /// </summary>
        internal static string GerarSintaxe_msg1409 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra.
        /// </summary>
        internal static string GerarSintaxe_msg1501 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1501", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1503 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1503", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando SE. Opções: = &gt; &gt;= &lt; &lt;= &lt;&gt; LIKE.
        /// </summary>
        internal static string GerarSintaxe_msg1505 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1505", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido &apos;##TOKEN1##&apos; para o Comando SE. Opções: Vazio, &apos;E&apos; ou &apos;OU&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1506 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1506", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualificadores não são permitidos em Palavra no comando SE. Use no campo Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1507 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1507", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] só armazena itens com dados da Palavra &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1508 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1508", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] não existe neste Pacote de Simulação.
        /// </summary>
        internal static string GerarSintaxe_msg1509 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1509", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando SE utilizando Qualificador. Opções: = &lt;&gt;.
        /// </summary>
        internal static string GerarSintaxe_msg1510 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1510", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg1511 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1511", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Constante Literal para esta Palavra deve conter ##TOKEN1## dígito(s) (zeros á esquerda).
        /// </summary>
        internal static string GerarSintaxe_msg1512 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1512", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando SE utilizando Palavra/Constante cujo Conteúdo é Alfanumérico. Opções: = &lt;&gt;.
        /// </summary>
        internal static string GerarSintaxe_msg1513 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1513", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg1514 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1514", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg1515 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1515", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE, utilizando Datas, permite apenas comparações entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1516 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1516", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto para o uso de Constante Literal para DATA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1517 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1517", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] só armazena itens com dados da Palavra &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1518 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1518", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] não existe.
        /// </summary>
        internal static string GerarSintaxe_msg1519 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1519", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os números informados na Constante não representam uma Hora. O Formato correto para o uso de Constante Literal para HORA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1520 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1520", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1521 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1521", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMANDO é Obrigatório.
        /// </summary>
        internal static string GerarSintaxe_msg1522 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1522", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. Na expressão ##TOKEN1## é obrigatório um operador CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1523 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1523", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr complementos.
        /// </summary>
        internal static string GerarSintaxe_msg1524 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1524", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1525 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1525", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SENAO não pertence a nenhum SE.
        /// </summary>
        internal static string GerarSintaxe_msg1526 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1526", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Um Comando SE não permite dois &apos;SENAO&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1527 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1527", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os números informados na Constante não representam uma Data. O Formato correto para o uso de Constante Literal para DATA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1528 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1528", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto para o uso de Constante Literal para HORA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1529 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1529", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIM SE não possui o seu respectivo &apos;SE&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1530 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1530", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE não possue seu respectivo FIM SE.
        /// </summary>
        internal static string GerarSintaxe_msg1531 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1531", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE necessita conter alguma expressão.
        /// </summary>
        internal static string GerarSintaxe_msg1532 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1532", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE necessita conter alguma expressão antes do seu SENAO.
        /// </summary>
        internal static string GerarSintaxe_msg1533 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1533", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SENAO necessita conter alguma expressão antes do seu FIM SE.
        /// </summary>
        internal static string GerarSintaxe_msg1534 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1534", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE, utilizando Datas, permite apenas comparações entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1535 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1535", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr complementos.
        /// </summary>
        internal static string GerarSintaxe_msg1538 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1538", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1539 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1539", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada &apos;##TOKEN1##&apos; para o Operador LIKE deve ser um texto entre aspas contendo o caracter curinga %.
        /// </summary>
        internal static string GerarSintaxe_msg1540 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1540", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O texto informado &apos;##TOKEN1##&apos; no Operador LIKE deve ser possuir um caracter curinga % no Início e/ou no Final do texto a procurar.
        /// </summary>
        internal static string GerarSintaxe_msg1541 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1541", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O texto informado &apos;##TOKEN1##&apos; no Operador LIKE deve ser possuir algum conteúdo relevante para pesquisa e não apenas curingas %.
        /// </summary>
        internal static string GerarSintaxe_msg1542 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1542", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando SE utilizando Palavra com comportamento BIT. Opções: = &lt;&gt;.
        /// </summary>
        internal static string GerarSintaxe_msg1543 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1543", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada &apos;##TOKEN1##&apos; utilizando Palavra com comportamento BIT deve ser um texto entre aspas.
        /// </summary>
        internal static string GerarSintaxe_msg1544 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1544", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada utilizando Palavra com comportamento BIT deve ser, entre aspas, apenas TRUE ou FALSE.
        /// </summary>
        internal static string GerarSintaxe_msg1545 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1545", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra.
        /// </summary>
        internal static string GerarSintaxe_msg1601 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1601", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1603 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1603", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando CALCULA. Opções: = + - * / %.
        /// </summary>
        internal static string GerarSintaxe_msg1605 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1605", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando CALCULA. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1606 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1606", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg1607 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1607", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA, utilizando Datas, apenas o sinal &apos;##TOKEN1##&apos; é permitido.
        /// </summary>
        internal static string GerarSintaxe_msg1608 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1608", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA, utilizando Datas, permite apenas cálculos entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1609 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1609", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA necessita que a Palavra informada possa ter seu Contéudo alterável.
        /// </summary>
        internal static string GerarSintaxe_msg1610 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1610", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra informada não tem Tipo de Dado (##TOKEN1##) compatível com o comando CALCULA.
        /// </summary>
        internal static string GerarSintaxe_msg1611 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1611", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1612 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1612", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA, utilizando Datas, permite apenas cálculos entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1613 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1613", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA não permite alteração do conteúdo das palavras com final ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg1614 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1614", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando CALCULA não possue Definição de Cálculo usando &apos;##TOKEN1##&apos; na Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1615 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1615", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra.
        /// </summary>
        internal static string GerarSintaxe_msg1701 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1701", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1703 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1703", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido para o Comando MOVE. Deve ser &apos;=&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1705 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1705", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando MOVE. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1706 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1706", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra informada &apos;##TOKEN1##&apos; não permite alteração de seu Conteúdo.
        /// </summary>
        internal static string GerarSintaxe_msg1707 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1707", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipos de Conteúdo de Palavra (##TOKEN1##) e Constante (##TOKEN2##) devem ser idênticos.
        /// </summary>
        internal static string GerarSintaxe_msg1708 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1708", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra &apos;##TOKEN1##&apos; apenas pode receber conteúdo de &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1709 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1709", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1710 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1710", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra.
        /// </summary>
        internal static string GerarSintaxe_msg1801 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1801", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualificadores só aceitam Palavras.
        /// </summary>
        internal static string GerarSintaxe_msg1803 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1803", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar um Qualificador em Constante.
        /// </summary>
        internal static string GerarSintaxe_msg1804 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1804", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Constante [ ##TOKEN1## ] não é um Qualificador.
        /// </summary>
        internal static string GerarSintaxe_msg1806 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1806", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido para o Comando ##TOKEN1##. Deve ser &apos;@&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1807 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1807", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continua inválido para o Comando ##TOKEN1##. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg1808 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1808", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] só armazena itens com dados da Palavra &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1811 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1811", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] não existe neste Pacote de Simulação.
        /// </summary>
        internal static string GerarSintaxe_msg1812 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1812", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1813 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1813", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] só armazena itens com dados da Palavra &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg1814 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1814", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] não existe.
        /// </summary>
        internal static string GerarSintaxe_msg1815 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1815", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr complementos.
        /// </summary>
        internal static string GerarSintaxe_msg1901 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1901", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg1902 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg1902", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra, um Registrador ou conteúdo constante.
        /// </summary>
        internal static string GerarSintaxe_msg2001 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg2002 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr nada a mais que uma Palavra, um Registrador ou um conteúdo constante.
        /// </summary>
        internal static string GerarSintaxe_msg2004 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regra deve conter Expressões.
        /// </summary>
        internal static string GerarSintaxe_msg2101 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regra deve conter um Comando FIM REGRA na útima expressão.
        /// </summary>
        internal static string GerarSintaxe_msg2102 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Comando ##TOKEN1## é obrigatório informar, ao menos, o parâmetro 01 de Retorno.
        /// </summary>
        internal static string GerarSintaxe_msg2201 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2201", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 01 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2202 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2202", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 01 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2203 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2203", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 02 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2204 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2204", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 02 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2205 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2205", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 03 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2206 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2206", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 03 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2207 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2207", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O comando ##TOKEN1## só permite até 03 parâmetros de retorno.
        /// </summary>
        internal static string GerarSintaxe_msg2208 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2208", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SE construído com erro. A última expressão de um SE, não pode conter um operador Lógico em CONTINUA.
        /// </summary>
        internal static string GerarSintaxe_msg2209 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2209", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 01 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2210 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2210", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 02 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2211 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 03 de retorno [ ##TOKEN1## ] deve estar contido entre Aspas no comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2212 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2212", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 01 de Retorno &apos;##TOKEN1##&apos; não pode exceder de 40 caracteres, incluindo as aspas.
        /// </summary>
        internal static string GerarSintaxe_msg2213 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2213", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 02 de Retorno &apos;##TOKEN1##&apos; não pode exceder de 40 caracteres, incluindo as aspas.
        /// </summary>
        internal static string GerarSintaxe_msg2214 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2214", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro 03 de Retorno &apos;##TOKEN1##&apos; não pode exceder de 80 caracteres, incluindo as aspas.
        /// </summary>
        internal static string GerarSintaxe_msg2215 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2215", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código Configuração Mensagem informado na Expressão [ ##TOKEN1## ] deve ser Maior que ZERO e Menor que 2.147.483.647.
        /// </summary>
        internal static string GerarSintaxe_msg2216 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2216", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código Configuração Mensagem informado na Expressão [ ##TOKEN1## ] não pode ser utilizado. ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2218 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2218", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Código Configuração Mensagem informado na Expressão [ ##TOKEN1## ] deve ser Numérico.
        /// </summary>
        internal static string GerarSintaxe_msg2219 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2219", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## DEVE ter, na sequência, o comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2301 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2301", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## DEVE ter, na sequência, o comando ##TOKEN2##.
        /// </summary>
        internal static string GerarSintaxe_msg2302 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2302", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Palavra.
        /// </summary>
        internal static string GerarSintaxe_msg2401 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2401", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg2402 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2402", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obrigatório informar uma Constante.
        /// </summary>
        internal static string GerarSintaxe_msg2403 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2403", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando TRSCONTAR. Opções: = &gt; &gt;= &lt; &lt;= &lt;&gt; LIKE.
        /// </summary>
        internal static string GerarSintaxe_msg2405 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2405", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTINUA inválido para o Comando TRSCONTAR. Deve estar vazio.
        /// </summary>
        internal static string GerarSintaxe_msg2406 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2406", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] só armazena itens com dados da Palavra &apos;##TOKEN2##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2408 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2408", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Qualificador [ ##TOKEN1## ] não existe neste Pacote de Simulação.
        /// </summary>
        internal static string GerarSintaxe_msg2409 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2409", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando TRSCONTAR utilizando Qualificador. Opções: = &lt;&gt;.
        /// </summary>
        internal static string GerarSintaxe_msg2410 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2410", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg2411 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2411", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Constante Literal para esta Palavra deve conter ##TOKEN1## dígito(s) (zeros á esquerda).
        /// </summary>
        internal static string GerarSintaxe_msg2412 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2412", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o Comando TRSCONTAR utilizando Palavra/Constante cujo Conteúdo é Alfanumérico. Opções: = &lt;&gt; LIKE.
        /// </summary>
        internal static string GerarSintaxe_msg2413 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2413", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg2414 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2414", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada não tem Tipo de Dado (##TOKEN1##) do mesmo tipo que Palavra (##TOKEN2##).
        /// </summary>
        internal static string GerarSintaxe_msg2415 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2415", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE, utilizando Datas, permite apenas comparações entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2416 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2416", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto para o uso de Constante Literal para DATA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg2417 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2417", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os números informados na Constante não representam uma Data. O Formato correto para o uso de Constante Literal para DATA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg2418 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2418", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O formato correto para o uso de Constante Literal para HORA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg2419 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2419", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Os números informados na Constante não representam uma Hora. O Formato correto para o uso de Constante Literal para HORA é ##TOKEN1##.
        /// </summary>
        internal static string GerarSintaxe_msg2420 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2420", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TRSCONTAR construído com erro. É necessário informar o término do TRSCONTAR acima na Regra com o respectivo FIM TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2421 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2421", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to COMANDO é Obrigatório.
        /// </summary>
        internal static string GerarSintaxe_msg2422 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2422", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando ##TOKEN1## não pode contêr complementos.
        /// </summary>
        internal static string GerarSintaxe_msg2423 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2423", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FIM TRSCONTAR não possui o seu respectivo &apos;TRSCONTAR&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2424 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2424", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Palavra &apos;##TOKEN1##&apos; não é permitida como Filtro no Comando TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2425 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2425", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Somente é permitido informar PALAVRAS (&apos;##TOKEN1##&apos;) no Comando TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2426 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2426", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando SE, utilizando Datas, permite apenas comparações entre ou duas &apos;Datas&apos; ou duas &apos;Horas&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2427 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2427", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sinal inválido &apos;##TOKEN1##&apos; para o parâmetro &apos;##TOKEN2##&apos; no Comando TRSCONTAR. Utilize =.
        /// </summary>
        internal static string GerarSintaxe_msg2428 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2428", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;##TOKEN1##&apos; no Comando TRSCONTAR só aceita um número MENOR ou Igual a Zero.
        /// </summary>
        internal static string GerarSintaxe_msg2429 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2429", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;##TOKEN1##&apos; no Comando TRSCONTAR só aceita um número INTEIRO.
        /// </summary>
        internal static string GerarSintaxe_msg2430 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2430", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido &apos;##TOKEN1##&apos; no parâmetro &apos;##TOKEN2##&apos; no Comando TRSCONTAR. Deve ser um número MENOR ou Igual a Zero.
        /// </summary>
        internal static string GerarSintaxe_msg2431 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2431", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Valor &apos;##TOKEN1##&apos; do parâmetro &apos;##TOKEN2##&apos; no Comando TRSCONTAR deve ser MENOR ou Igual a Zero.
        /// </summary>
        internal static string GerarSintaxe_msg2432 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2432", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor inválido &apos;##TOKEN1##&apos; no parâmetro &apos;##TOKEN2##&apos; no Comando TRSCONTAR. Deve ser um número MENOR ou Igual a Zero.
        /// </summary>
        internal static string GerarSintaxe_msg2433 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2433", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;PERIODOTERMINO&apos; no Comando TRSCONTAR deve ser ##TOKEN1## que o parâmetro &apos;PERIODOINICIO&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2434 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2434", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante informada &apos;##TOKEN1##&apos; para o Operador LIKE deve ser um texto entre aspas contendo o caracter curinga %.
        /// </summary>
        internal static string GerarSintaxe_msg2440 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2440", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O texto informado &apos;##TOKEN1##&apos; no Operador LIKE deve ser possuir um caracter curinga % no Início e/ou no Final do texto a procurar.
        /// </summary>
        internal static string GerarSintaxe_msg2441 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2441", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O texto informado &apos;##TOKEN1##&apos; no Operador LIKE deve ser possuir algum conteúdo relevante para pesquisa e não apenas curingas %.
        /// </summary>
        internal static string GerarSintaxe_msg2442 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2442", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;PERIODOINICIO&apos; é Obrigatório no Comando TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2443 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2443", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O parâmetro &apos;PERIODOTERMINO&apos; é Obrigatório no Comando TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2444 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2444", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Existe um comando TRSCONTAR sem o respectivo FIM TRSCONTAR.
        /// </summary>
        internal static string GerarSintaxe_msg2445 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2445", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comando Inválido &apos;##TOKEN1##&apos;.
        /// </summary>
        internal static string GerarSintaxe_msg2999 {
            get {
                return ResourceManager.GetString("GerarSintaxe_msg2999", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O Número informado na Expressão [ ##TOKEN1## ] está acima do limite permitido (Limite = 999.999.999.999.999.999).
        /// </summary>
        internal static string ObtemIdentificadorTipo_msg01 {
            get {
                return ResourceManager.GetString("ObtemIdentificadorTipo_msg01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Constante AlfaNumérica [ ##TOKEN1## ] deve estar contida entre Aspas.
        /// </summary>
        internal static string ObtemIdentificadorTipo_msg02 {
            get {
                return ResourceManager.GetString("ObtemIdentificadorTipo_msg02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra  [ ##TOKEN1## ] não pode ser utilizada no Construtor de Expressões de Regras.
        /// </summary>
        internal static string ObtemIdentificadorTipo_msg03 {
            get {
                return ResourceManager.GetString("ObtemIdentificadorTipo_msg03", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra, Registrador ou Qualificador &apos;##TOKEN1##&apos; não existe no Pacote de Simulação ID ##TOKEN2##.
        /// </summary>
        internal static string ObtemIdentificadorTipo_msg04 {
            get {
                return ResourceManager.GetString("ObtemIdentificadorTipo_msg04", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Palavra, Registrador ou Qualificador &apos;##TOKEN1##&apos; não existe.
        /// </summary>
        internal static string ObtemIdentificadorTipo_msg05 {
            get {
                return ResourceManager.GetString("ObtemIdentificadorTipo_msg05", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido alterar o Status &apos;Ativo&apos; desta Regra pois existe(m) comando(s) IR PARA referenciando esta Regra. Estes se encontram em:.
        /// </summary>
        internal static string PreChecagemAlteracaoStatusAtivo_IRPARA_Producao_msgNaoAlterarStatus {
            get {
                return ResourceManager.GetString("PreChecagemAlteracaoStatusAtivo_IRPARA_Producao_msgNaoAlterarStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não é permitido alterar o Status &apos;Ativo&apos; desta Regra pois existe(m) comando(s) IR PARA referenciando esta Regra. Estes se encontram em:.
        /// </summary>
        internal static string PreChecagemAlteracaoStatusAtivo_IRPARA_Simulacao_msgNaoAlterarStatus {
            get {
                return ResourceManager.GetString("PreChecagemAlteracaoStatusAtivo_IRPARA_Simulacao_msgNaoAlterarStatus", resourceCulture);
            }
        }
    }
}
