//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.BRM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SimulacaoPacoteTransacao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SimulacaoPacoteTransacao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.BRM.SimulacaoPacoteTransacao", typeof(SimulacaoPacoteTransacao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string Data {
            get {
                return ResourceManager.GetString("Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Hora.
        /// </summary>
        internal static string Data_Hora {
            get {
                return ResourceManager.GetString("Data_Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dom.
        /// </summary>
        internal static string Domingo {
            get {
                return ResourceManager.GetString("Domingo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora.
        /// </summary>
        internal static string Hora {
            get {
                return ResourceManager.GetString("Hora", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qua.
        /// </summary>
        internal static string Quarta {
            get {
                return ResourceManager.GetString("Quarta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qui.
        /// </summary>
        internal static string Quinta {
            get {
                return ResourceManager.GetString("Quinta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sáb.
        /// </summary>
        internal static string Sabado {
            get {
                return ResourceManager.GetString("Sabado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seg.
        /// </summary>
        internal static string Segunda {
            get {
                return ResourceManager.GetString("Segunda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sex.
        /// </summary>
        internal static string Sexta {
            get {
                return ResourceManager.GetString("Sexta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ter.
        /// </summary>
        internal static string Terca {
            get {
                return ResourceManager.GetString("Terca", resourceCulture);
            }
        }
    }
}
