//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class GlobalGenerico {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal GlobalGenerico() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.GlobalGenerico", typeof(GlobalGenerico).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Todos.
        /// </summary>
        internal static string Todos {
            get {
                return ResourceManager.GetString("Todos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ano(s).
        /// </summary>
        internal static string ValidadePeriodo_ANO_Texto {
            get {
                return ResourceManager.GetString("ValidadePeriodo_ANO_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dia(s).
        /// </summary>
        internal static string ValidadePeriodo_DIA_Texto {
            get {
                return ResourceManager.GetString("ValidadePeriodo_DIA_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hora(s).
        /// </summary>
        internal static string ValidadePeriodo_HOR_Texto {
            get {
                return ResourceManager.GetString("ValidadePeriodo_HOR_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mês(es).
        /// </summary>
        internal static string ValidadePeriodo_MES_Texto {
            get {
                return ResourceManager.GetString("ValidadePeriodo_MES_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minuto(s).
        /// </summary>
        internal static string ValidadePeriodo_MIN_Texto {
            get {
                return ResourceManager.GetString("ValidadePeriodo_MIN_Texto", resourceCulture);
            }
        }
    }
}
