//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.Mensageria {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StatusMensagem {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatusMensagem() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.Mensageria.StatusMensagem", typeof(StatusMensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente de Resposta (no prazo) - Mensagem Enviada.
        /// </summary>
        internal static string StatusMensagem_ENV {
            get {
                return ResourceManager.GetString("StatusMensagem_ENV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente de Resposta (no prazo) - Mensagem Lida.
        /// </summary>
        internal static string StatusMensagem_ENVML {
            get {
                return ResourceManager.GetString("StatusMensagem_ENVML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente de Resposta (no prazo) - Mensagem Recebida.
        /// </summary>
        internal static string StatusMensagem_ENVMR {
            get {
                return ResourceManager.GetString("StatusMensagem_ENVMR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro.
        /// </summary>
        internal static string StatusMensagem_RETER {
            get {
                return ResourceManager.GetString("StatusMensagem_RETER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pendente de Resposta (Prazo Expirado).
        /// </summary>
        internal static string StatusMensagem_RETEX {
            get {
                return ResourceManager.GetString("StatusMensagem_RETEX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta não Identificada.
        /// </summary>
        internal static string StatusMensagem_RETNI {
            get {
                return ResourceManager.GetString("StatusMensagem_RETNI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Reconhecido pelo Cliente.
        /// </summary>
        internal static string StatusMensagem_RETNR {
            get {
                return ResourceManager.GetString("StatusMensagem_RETNR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconhecido pelo Cliente.
        /// </summary>
        internal static string StatusMensagem_RETRE {
            get {
                return ResourceManager.GetString("StatusMensagem_RETRE", resourceCulture);
            }
        }
    }
}
