//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AcaoExterna {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcaoExterna() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.Global.AcaoExterna", typeof(AcaoExterna).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloquear Cartão no sistema Corporativo.
        /// </summary>
        internal static string AcaoExterna_CRT_BLOQUEAR_NO_CORP_Texto {
            get {
                return ResourceManager.GetString("AcaoExterna_CRT_BLOQUEAR_NO_CORP_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloquear Cartão no sistema Corporativo.
        /// </summary>
        internal static string AcaoExterna_CRT_DESBLOQUEAR_NO_CORP_Texto {
            get {
                return ResourceManager.GetString("AcaoExterna_CRT_DESBLOQUEAR_NO_CORP_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bloqueado no sistema Corporativo.
        /// </summary>
        internal static string AcaoExternaSituacao_CRT_BLOQUEADO_Texto {
            get {
                return ResourceManager.GetString("AcaoExternaSituacao_CRT_BLOQUEADO_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelado no sistema Corporativo.
        /// </summary>
        internal static string AcaoExternaSituacao_CRT_CANCELADO_Texto {
            get {
                return ResourceManager.GetString("AcaoExternaSituacao_CRT_CANCELADO_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desbloqueado no sistema Corporativo.
        /// </summary>
        internal static string AcaoExternaSituacao_CRT_DESBLOQUEADO_Texto {
            get {
                return ResourceManager.GetString("AcaoExternaSituacao_CRT_DESBLOQUEADO_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao acessar o sistema Corporativo.
        /// </summary>
        internal static string AcaoExternaSituacao_CRT_ERRODEACESSO_Texto {
            get {
                return ResourceManager.GetString("AcaoExternaSituacao_CRT_ERRODEACESSO_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não Existe no sistema Corporativo.
        /// </summary>
        internal static string AcaoExternaSituacao_CRT_NAOEXISTE_Texto {
            get {
                return ResourceManager.GetString("AcaoExternaSituacao_CRT_NAOEXISTE_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de parâmetro escolhido. Não foi possível enviar para o WebService a solicitação de Bloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Bloquear_Erro_Parametro {
            get {
                return ResourceManager.GetString("Mensagem_Bloquear_Erro_Parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorre um erro. Não foi possível enviar para o WebService a solicitação de Bloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Bloquear_Exception_RptErrUserMsg {
            get {
                return ResourceManager.GetString("Mensagem_Bloquear_Exception_RptErrUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter o cartão no Portal. Não foi possível enviar para o WebService a solicitação de Bloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Bloquear_Falha {
            get {
                return ResourceManager.GetString("Mensagem_Bloquear_Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro de parâmetro escolhido. Não foi possível enviar para o WebService a solicitação de Desbloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Desbloquear_Erro_Parametro {
            get {
                return ResourceManager.GetString("Mensagem_Desbloquear_Erro_Parametro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorre um erro. Não foi possível enviar para o WebService a solicitação de Desbloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Desbloquear_Exception_RptErrUserMsg {
            get {
                return ResourceManager.GetString("Mensagem_Desbloquear_Exception_RptErrUserMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter o cartão no Portal. Não foi possível enviar para o WebService a solicitação de Desbloqueio do Cartão.
        /// </summary>
        internal static string Mensagem_Desbloquear_Falha {
            get {
                return ResourceManager.GetString("Mensagem_Desbloquear_Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Falha ao obter o cartão no Portal. Não foi possível enviar para o WebService a solicitação de verificar o status do Cartão.
        /// </summary>
        internal static string Mensagem_ObterAcaoExterna_Situacao_Falha {
            get {
                return ResourceManager.GetString("Mensagem_ObterAcaoExterna_Situacao_Falha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao verificar status do cartão.
        /// </summary>
        internal static string ObterAcaoExterna_Situacao_Exception_RptErrUserMsg {
            get {
                return ResourceManager.GetString("ObterAcaoExterna_Situacao_Exception_RptErrUserMsg", resourceCulture);
            }
        }
    }
}
