//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.Global {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AcaoExternaExecucao {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AcaoExternaExecucao() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.Global.AcaoExternaExecucao", typeof(AcaoExternaExecucao).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de bloqueio enviada com sucesso para o Sistema Corporativo.
        /// </summary>
        internal static string Mensagem_Bloqueio_Efetivado {
            get {
                return ResourceManager.GetString("Mensagem_Bloqueio_Efetivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de bloqueio enviada para o Sistema Corporativo, porém a mesma não pode ser efetivada.
        /// </summary>
        internal static string Mensagem_Bloqueio_Nao_Efetivado {
            get {
                return ResourceManager.GetString("Mensagem_Bloqueio_Nao_Efetivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de bloqueio enviada para o Sistema Corporativo, porém a mesma não pode ser efetivada [ Cartão ##TOKEN1## ].
        /// </summary>
        internal static string Mensagem_Bloqueio_Nao_Efetivado_Logar {
            get {
                return ResourceManager.GetString("Mensagem_Bloqueio_Nao_Efetivado_Logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WebService do sistema Corporativo encontra-se indisponível para bloquear o cartão.
        /// </summary>
        internal static string Mensagem_Bloqueio_WS_INDISPONIVEL {
            get {
                return ResourceManager.GetString("Mensagem_Bloqueio_WS_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de desbloqueio enviada com sucesso para o Sistema Corporativo.
        /// </summary>
        internal static string Mensagem_Desbloqueio_Efetivado {
            get {
                return ResourceManager.GetString("Mensagem_Desbloqueio_Efetivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de desbloqueio enviada para o Sistema Corporativo, porém a mesma não pode ser efetivada.
        /// </summary>
        internal static string Mensagem_Desbloqueio_Não_Efetivado {
            get {
                return ResourceManager.GetString("Mensagem_Desbloqueio_Não_Efetivado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solicitação de desbloqueio enviada para o Sistema Corporativo, porém a mesma não pode ser efetivada [ Cartão ##TOKEN1## ].
        /// </summary>
        internal static string Mensagem_Desbloqueio_Não_Efetivado_Logar {
            get {
                return ResourceManager.GetString("Mensagem_Desbloqueio_Não_Efetivado_Logar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WebService do sistema Corporativo encontra-se indisponível para desbloquear o cartão.
        /// </summary>
        internal static string Mensagem_Desbloqueio_WS_INDISPONIVEL {
            get {
                return ResourceManager.GetString("Mensagem_Desbloqueio_WS_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão encontra-se Bloqueado no sistema Corporativo..
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_CRT_BLOQUEADO {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_CRT_BLOQUEADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão encontra-se Cancelado no sistema Corporativo.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_CRT_CANCELADO {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_CRT_CANCELADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O cartão encontra-se Desbloqueado no sistema Corporativo.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_CRT_DESBLOQUEADO {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_CRT_DESBLOQUEADO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocorreu um erro ao acessar o WebService do sistema Corporativo.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_CRT_ERRODEACESSO {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_CRT_ERRODEACESSO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão não encontrado no sistema Corporativo.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_CRT_NAOEXISTE {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_CRT_NAOEXISTE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WebService do sistema Corporativo encontra-se indisponível.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_WS_INDISPONIVEL {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_WS_INDISPONIVEL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O WebService não existe ou foi configurado errado.
        /// </summary>
        internal static string Mensagem_GetSituacaoCartao_WS_NAOEXISTE {
            get {
                return ResourceManager.GetString("Mensagem_GetSituacaoCartao_WS_NAOEXISTE", resourceCulture);
            }
        }
    }
}
