//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.ALM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Analise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Analise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.ALM.Analise", typeof(Analise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prévia Restrição.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_Default {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Iniciar Nova Análise.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__GO {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__GO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alerta Expirado na Fila.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__ALERTA_EXPIRADO_NA_FILA {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__ALERTA_EXPIRADO_NA_FILA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Agendamento.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_AGENDAMENTO {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_AGENDAMENTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Bloqueio Preventivo.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_BLOQ_PREVENTIVO {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_BLOQ_PREVENTIVO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Reanálise.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_REANALISE {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__CARTAO_REANALISE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão em Análise.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__ENVELOPE_ANALISE_ABERTO {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__ENVELOPE_ANALISE_ABERTO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restrições da Estratégia atual.
        /// </summary>
        internal static string ChecagemTRS_Veredicto_TRS__NO_GO__ESTRATEGIA {
            get {
                return ResourceManager.GetString("ChecagemTRS_Veredicto_TRS__NO_GO__ESTRATEGIA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checagem não autorizou abertura de nova Análise utilizando esse Alerta.
        /// </summary>
        internal static string retornoGeracao_ChecagemNaoAutorizouNovaAnaliseEsteAlerta {
            get {
                return ResourceManager.GetString("retornoGeracao_ChecagemNaoAutorizouNovaAnaliseEsteAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não foi possível obter a Transação ID ##TOKEN1##.
        /// </summary>
        internal static string retornoGeracao_NaoFoiPossivelObterTransacao {
            get {
                return ResourceManager.GetString("retornoGeracao_NaoFoiPossivelObterTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Não há Alertas nas Filas para este Cartão
        ///( IdCartao = ##TOKEN1## ).
        /// </summary>
        internal static string retornoGeracao_NaoHaAlertasParaEsteCartao {
            get {
                return ResourceManager.GetString("retornoGeracao_NaoHaAlertasParaEsteCartao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Já foi iniciada uma Nova Análise para este Cartão por outro Usuário.
        /// </summary>
        internal static string retornoGeracao_NovaAnaliseJaIniciadoPorOutroUsuario {
            get {
                return ResourceManager.GetString("retornoGeracao_NovaAnaliseJaIniciadoPorOutroUsuario", resourceCulture);
            }
        }
    }
}
