//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.ALM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvelopeAnaliseVisualizacaoCampo {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvelopeAnaliseVisualizacaoCampo() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.ALM.EnvelopeAnaliseVisualizacaoCampo", typeof(EnvelopeAnaliseVisualizacaoCampo).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neural - ID Score.
        /// </summary>
        internal static string AutorizacaoIdScoreNeural {
            get {
                return ResourceManager.GetString("AutorizacaoIdScoreNeural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorização Rede Neural.
        /// </summary>
        internal static string AutorizacaoRedeNeural {
            get {
                return ResourceManager.GetString("AutorizacaoRedeNeural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autorização Score Neural.
        /// </summary>
        internal static string AutorizacaoScoreNeural {
            get {
                return ResourceManager.GetString("AutorizacaoScoreNeural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Viagem Data Final.
        /// </summary>
        internal static string AvisoViagemDataFinal {
            get {
                return ResourceManager.GetString("AvisoViagemDataFinal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aviso Viagem Data Inicial.
        /// </summary>
        internal static string AvisoViagemDataInicial {
            get {
                return ResourceManager.GetString("AvisoViagemDataInicial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Banco AgênciaConta Dígito Verif.
        /// </summary>
        internal static string BancoAgenciaContaDigitoVerif {
            get {
                return ResourceManager.GetString("BancoAgenciaContaDigitoVerif", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bco. Ag. Transação.
        /// </summary>
        internal static string BancoAgenciaTransacao {
            get {
                return ResourceManager.GetString("BancoAgenciaTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bandeira.
        /// </summary>
        internal static string Bandeira {
            get {
                return ResourceManager.GetString("Bandeira", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BIN.
        /// </summary>
        internal static string BIN {
            get {
                return ResourceManager.GetString("BIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agência Cartão.
        /// </summary>
        internal static string CartaoAgencia {
            get {
                return ResourceManager.GetString("CartaoAgencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CEP Estab..
        /// </summary>
        internal static string CepEstabelecimento {
            get {
                return ResourceManager.GetString("CepEstabelecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cidade Estabelecimento.
        /// </summary>
        internal static string CidadeEstabelecimento {
            get {
                return ResourceManager.GetString("CidadeEstabelecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CPF - CNPJ.
        /// </summary>
        internal static string ClienteCpfCnpj {
            get {
                return ResourceManager.GetString("ClienteCpfCnpj", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acquirer.
        /// </summary>
        internal static string CodigoAcquirer {
            get {
                return ResourceManager.GetString("CodigoAcquirer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Bco. Transação.
        /// </summary>
        internal static string CodigoBancoTransacao {
            get {
                return ResourceManager.GetString("CodigoBancoTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Estab..
        /// </summary>
        internal static string CodigoEstabelecimento {
            get {
                return ResourceManager.GetString("CodigoEstabelecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Ramo Atividade.
        /// </summary>
        internal static string CodigoRamoAtividade {
            get {
                return ResourceManager.GetString("CodigoRamoAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Resposta.
        /// </summary>
        internal static string CodigoResposta {
            get {
                return ResourceManager.GetString("CodigoResposta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cód. Terminal.
        /// </summary>
        internal static string CodigoTerminal {
            get {
                return ResourceManager.GetString("CodigoTerminal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data/Hora Transação.
        /// </summary>
        internal static string DataHoraTransacao {
            get {
                return ResourceManager.GetString("DataHoraTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Ramo Atividade.
        /// </summary>
        internal static string DescricaoRamoAtividade {
            get {
                return ResourceManager.GetString("DescricaoRamoAtividade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descrição Reason Code.
        /// </summary>
        internal static string DescricaoReasonCode {
            get {
                return ResourceManager.GetString("DescricaoReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device ID1.
        /// </summary>
        internal static string DeviceID1 {
            get {
                return ResourceManager.GetString("DeviceID1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Language Code.
        /// </summary>
        internal static string DeviceLanguageCode {
            get {
                return ResourceManager.GetString("DeviceLanguageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Number.
        /// </summary>
        internal static string DeviceNumber {
            get {
                return ResourceManager.GetString("DeviceNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Type.
        /// </summary>
        internal static string DeviceType {
            get {
                return ResourceManager.GetString("DeviceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dígito Agência Transação.
        /// </summary>
        internal static string DigitoAgenciaTransacao {
            get {
                return ResourceManager.GetString("DigitoAgenciaTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dígito Conta Transação.
        /// </summary>
        internal static string DigitoContaTransacao {
            get {
                return ResourceManager.GetString("DigitoContaTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grupo.
        /// </summary>
        internal static string Grupo {
            get {
                return ResourceManager.GetString("Grupo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Fila.
        /// </summary>
        internal static string IdFila {
            get {
                return ResourceManager.GetString("IdFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id Transação.
        /// </summary>
        internal static string IdTransacao {
            get {
                return ResourceManager.GetString("IdTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Recebida.
        /// </summary>
        internal static string InterfaceRecebida {
            get {
                return ResourceManager.GetString("InterfaceRecebida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude End. Res..
        /// </summary>
        internal static string LatitudeEnderecoResidencial {
            get {
                return ResourceManager.GetString("LatitudeEnderecoResidencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latitude Estab. Transação.
        /// </summary>
        internal static string LatitudeTransacao {
            get {
                return ResourceManager.GetString("LatitudeTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Limite Utilizado.
        /// </summary>
        internal static string LimiteUtilizado {
            get {
                return ResourceManager.GetString("LimiteUtilizado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        internal static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude End. Res..
        /// </summary>
        internal static string LongitudeEnderecoResidencial {
            get {
                return ResourceManager.GetString("LongitudeEnderecoResidencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Longitude Estab. Transação.
        /// </summary>
        internal static string LongitudeTransacao {
            get {
                return ResourceManager.GetString("LongitudeTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensagem Enviada.
        /// </summary>
        internal static string MensagemEnviada {
            get {
                return ResourceManager.GetString("MensagemEnviada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome Estabelecimento.
        /// </summary>
        internal static string NomeEstabelecimento {
            get {
                return ResourceManager.GetString("NomeEstabelecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nome da Fila.
        /// </summary>
        internal static string NomeFila {
            get {
                return ResourceManager.GetString("NomeFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nº Produto.
        /// </summary>
        internal static string NumeroProduto {
            get {
                return ResourceManager.GetString("NumeroProduto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Origem do Alerta.
        /// </summary>
        internal static string OrigemAlerta {
            get {
                return ResourceManager.GetString("OrigemAlerta", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outras Análises.
        /// </summary>
        internal static string OutrosEnvelopes {
            get {
                return ResourceManager.GetString("OutrosEnvelopes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PAN Source.
        /// </summary>
        internal static string PANSource {
            get {
                return ResourceManager.GetString("PANSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to % Compra.
        /// </summary>
        internal static string PercentualCompra {
            get {
                return ResourceManager.GetString("PercentualCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POS.
        /// </summary>
        internal static string POS {
            get {
                return ResourceManager.GetString("POS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Code.
        /// </summary>
        internal static string ReasonCode {
            get {
                return ResourceManager.GetString("ReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regra.
        /// </summary>
        internal static string Regra {
            get {
                return ResourceManager.GetString("Regra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resposta Anterior.
        /// </summary>
        internal static string RespostaAnterior {
            get {
                return ResourceManager.GetString("RespostaAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        internal static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moeda.
        /// </summary>
        internal static string SiglaMoeda {
            get {
                return ResourceManager.GetString("SiglaMoeda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País End. Res..
        /// </summary>
        internal static string SiglaPaisEnderecoResidencial {
            get {
                return ResourceManager.GetString("SiglaPaisEnderecoResidencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status Envelope Anterior.
        /// </summary>
        internal static string StatusEnvelopeAnterior {
            get {
                return ResourceManager.GetString("StatusEnvelopeAnterior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo de Fila.
        /// </summary>
        internal static string TipoDeFila {
            get {
                return ResourceManager.GetString("TipoDeFila", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Msg. Entrada.
        /// </summary>
        internal static string TipoMensagemEntrada {
            get {
                return ResourceManager.GetString("TipoMensagemEntrada", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tipo Pagamento Transação.
        /// </summary>
        internal static string TipoPagamentoTransacao {
            get {
                return ResourceManager.GetString("TipoPagamentoTransacao", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token ACC Score.
        /// </summary>
        internal static string TokenAccountScore {
            get {
                return ResourceManager.GetString("TokenAccountScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Age.
        /// </summary>
        internal static string TokenAge {
            get {
                return ResourceManager.GetString("TokenAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Ativo.
        /// </summary>
        internal static string TokenAtivo {
            get {
                return ResourceManager.GetString("TokenAtivo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Device Score.
        /// </summary>
        internal static string TokenDeviceScore {
            get {
                return ResourceManager.GetString("TokenDeviceScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Inativo.
        /// </summary>
        internal static string TokenInativo {
            get {
                return ResourceManager.GetString("TokenInativo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token PRV Score.
        /// </summary>
        internal static string TokenProvisioningScore {
            get {
                return ResourceManager.GetString("TokenProvisioningScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Reason Code.
        /// </summary>
        internal static string TokenReasonCode {
            get {
                return ResourceManager.GetString("TokenReasonCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Req ID.
        /// </summary>
        internal static string TokenRequestorId {
            get {
                return ResourceManager.GetString("TokenRequestorId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Suspenso.
        /// </summary>
        internal static string TokenSuspenso {
            get {
                return ResourceManager.GetString("TokenSuspenso", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token TR Counter.
        /// </summary>
        internal static string TokenTransactionCounter {
            get {
                return ResourceManager.GetString("TokenTransactionCounter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Type.
        /// </summary>
        internal static string TokenType {
            get {
                return ResourceManager.GetString("TokenType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bco. Conta Nr. Transação.
        /// </summary>
        internal static string TransacaoBancoContaNumero {
            get {
                return ResourceManager.GetString("TransacaoBancoContaNumero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to País Transacao.
        /// </summary>
        internal static string TransacaoSiglaPais {
            get {
                return ResourceManager.GetString("TransacaoSiglaPais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF End. Res..
        /// </summary>
        internal static string UFEnderecoResidencial {
            get {
                return ResourceManager.GetString("UFEnderecoResidencial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UF Estab..
        /// </summary>
        internal static string UfEstabelecimento {
            get {
                return ResourceManager.GetString("UfEstabelecimento", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Faturado.
        /// </summary>
        internal static string ValorFaturado {
            get {
                return ResourceManager.GetString("ValorFaturado", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de Crédito.
        /// </summary>
        internal static string ValorLimiteCredito {
            get {
                return ResourceManager.GetString("ValorLimiteCredito", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de Compra Disponível.
        /// </summary>
        internal static string ValorLimiteDisponivelCompra {
            get {
                return ResourceManager.GetString("ValorLimiteDisponivelCompra", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de Saque Disponível.
        /// </summary>
        internal static string ValorLimiteDisponivelSaque {
            get {
                return ResourceManager.GetString("ValorLimiteDisponivelSaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Limite de Saque.
        /// </summary>
        internal static string ValorLimiteSaque {
            get {
                return ResourceManager.GetString("ValorLimiteSaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valor Local.
        /// </summary>
        internal static string ValorLocal {
            get {
                return ResourceManager.GetString("ValorLocal", resourceCulture);
            }
        }
    }
}
