//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CaseBusiness.Resources.CC.ALM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnvelopeAnalise {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnvelopeAnalise() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CaseBusiness.Resources.CC.ALM.EnvelopeAnalise", typeof(EnvelopeAnalise).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Agendamento.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_CARTAO_AGEND_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_CARTAO_AGEND_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Bloqueio Preventivo.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_CARTAO_BLOQPREV_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_CARTAO_BLOQPREV_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cartão com Reanálise.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_CARTAO_REANALISE_Texto1 {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_CARTAO_REANALISE_Texto1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fila - Detalhe.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_FILA_DETALHE_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_FILA_DETALHE_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Alerta.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_PESQUISAR_ALERT_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_PESQUISAR_ALERT_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pesquisar Transação.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_PESQUISAR_TRS_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_PESQUISAR_TRS_Texto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seleção por Fila.
        /// </summary>
        internal static string FuncionalidadeInicioEnvelope_SELECAO_FILA_Texto {
            get {
                return ResourceManager.GetString("FuncionalidadeInicioEnvelope_SELECAO_FILA_Texto", resourceCulture);
            }
        }
    }
}
